apiVersion: v1
kind: Service
metadata:
  labels:
    app: blog
  name: srv-blog
  namespace: dev
spec:
  ports:
  - nodePort: 30080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: blog
  type: NodePort